# Generated by Django 5.1 on 2024-08-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('najdizmrzkuapp', '0003_rename_userprofile_user_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
