# Generated by Django 5.1 on 2024-08-26 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('najdizmrzkuapp', '0004_rename_user_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nick',
            new_name='username',
        ),
    ]
